In [31]:
import pandas as pd
import pymysql


def load_dbscore_data():
    xl_file = 'C:\Temp\Anaconda\db_score_3_labels.xlsx'
    db_score = pd.read_excel(xl_file)

    conn = pymysql.connect(host='localhost', user='root', password='dkfrpanjdi1~', db='datascience_week6', charset='utf8') 
    curs = conn.cursor(pymysql.cursors.DictCursor)

    make_table = 'create table if not exists db_score (sno int primary key, homework float, discussion float, final float, grade char)'
    curs.execute(make_table)

    sql = 'insert into db_score (sno, homework, discussion, final, grade) values(%s, %s, %s, %s, %s)'
    for i in range(len(db_score)):
        curs.execute(sql, tuple(db_score.values[i]))
    '''
    drop_sql = """drop table if exists db_score"""
    curs.execute(drop_sql)'''
    conn.commit()
    
    curs.close()
    conn.close()
    

load_dbscore_data()

IntegrityError: (1062, "Duplicate entry '1' for key 'db_score.PRIMARY'")

In [66]:
import pandas as pd
import pymysql
import numpy as np

def classification_performance_eval(y, y_predict):
    tp, tn, fp, fn = 0,0,0,0
    
    for y, yp in zip(y,y_predict):
        if y == 1 and yp == 1:
            tp += 1
        elif y == 1 and yp == 0:
            fn += 1
        elif y == 0 and yp == 1:
            fp += 1
        else:
            tn += 1
            
    accuracy = (tp+tn)/(tp+tn+fp+fn)
    precision = (tp)/(tp+fp)
    recall = (tp)/(tp+fn)
    f1_score = 2*precision*recall / (precision+recall)
    
    return accuracy, precision, recall, f1_score



conn = pymysql.connect(host='localhost', user='root', password='dkfrpanjdi1~', db='datascience_week6', charset='utf8') 
curs = conn.cursor(pymysql.cursors.DictCursor)
sql = "select * from db_score"
curs.execute(sql)

data  = curs.fetchall()

curs.close()
conn.close()

X = [ (t['homework'], t['discussion'], t['final']) for t in data ]
X = np.array(X)

y = [ 1 if (t['grade'] == 'B') else 0 for t in data]
y = np.array(y)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

print(y_test)


from sklearn import svm

clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)

y_predict = clf.predict(X_test)

print(y_predict)
acc, prec, rec, f1 = classification_performance_eval(y_test, y_predict)
print("accuracy=%f" %acc)
print("precision=%f" %prec)
print("recall=%f" %rec)
print("f1_score=%f" %f1)

[1 0 1 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 1 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


ZeroDivisionError: division by zero

In [67]:
import pandas as pd
import pymysql
import numpy as np

def classification_performance_eval(y, y_predict):
    tp, tn, fp, fn = 0,0,0,0
    
    for y, yp in zip(y,y_predict):
        if y == 1 and yp == 1:
            tp += 1
        elif y == 1 and yp == 0:
            fn += 1
        elif y == 0 and yp == 1:
            fp += 1
        else:
            tn += 1
            
    accuracy = (tp+tn)/(tp+tn+fp+fn)
    precision = (tp)/(tp+fp)
    recall = (tp)/(tp+fn)
    f1_score = 2*precision*recall / (precision+recall)
    
    return accuracy, precision, recall, f1_score



conn = pymysql.connect(host='localhost', user='root', password='dkfrpanjdi1~', db='datascience_week6', charset='utf8') 
curs = conn.cursor(pymysql.cursors.DictCursor)
sql = "select * from db_score"
curs.execute(sql)

data  = curs.fetchall()

curs.close()
conn.close()

X = [ (t['homework'], t['discussion'], t['final']) for t in data ]
X = np.array(X)

y = [ 1 if (t['grade'] == 'B') else 0 for t in data]
y = np.array(y)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

print(y_test)


from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
model = lr.fit(X_train, y_train)
y_predict = model.predict(X_test)

print(y_predict)

acc, prec, rec, f1 = classification_performance_eval(y_test, y_predict)
print("accuracy=%f" %acc)
print("precision=%f" %prec)
print("recall=%f" %rec)
print("f1_score=%f" %f1)

[1 0 1 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


ZeroDivisionError: division by zero

In [74]:
import pandas as pd
import pymysql
import numpy as np

def classification_performance_eval(y, y_predict):
    tp, tn, fp, fn = 0,0,0,0
    
    for y, yp in zip(y,y_predict):
        if y == 1 and yp == 1:
            tp += 1
        elif y == 1 and yp == 0:
            fn += 1
        elif y == 0 and yp == 1:
            fp += 1
        else:
            tn += 1
            
    accuracy = (tp+tn)/(tp+tn+fp+fn)
    precision = (tp)/(tp+fp)
    recall = (tp)/(tp+fn)
    f1_score = 2*precision*recall / (precision+recall)
    
    return accuracy, precision, recall, f1_score



conn = pymysql.connect(host='localhost', user='root', password='dkfrpanjdi1~', db='datascience_week6', charset='utf8') 
curs = conn.cursor(pymysql.cursors.DictCursor)
sql = "select * from db_score"
curs.execute(sql)

data  = curs.fetchall()

curs.close()
conn.close()

X = [ (t['homework'], t['discussion'], t['final']) for t in data ]
X = np.array(X)

y = [ 1 if (t['grade'] == 'B') else 0 for t in data]
y = np.array(y)

from sklearn.model_selection import KFold

accuracy = []
precision = []
recall = []
f1_score = []

kf = KFold(n_splits=5, random_state=42, shuffle=True)


from sklearn import svm

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    clf = svm.SVC(kernel='linear')
    clf.fit(X_train, y_train)
    print("test: ", y_test)

    y_predict = clf.predict(X_test)
    print("predict: ", y_predict)
        
    acc, prec, rec, f1 = classification_performance_eval(y_test, y_predict)
    accuracy.append(acc)
    precision.append(prec)
    recall.append(rec)
    f1_score.append(f1)


   
import statistics

print("average_accuracy =", statistics.mean(accuracy))
print("average_precision =", statistics.mean(precision))
print("average_recall =", statistics.mean(recall))
print("average_f1_score =", statistics.mean(f1_score))


test:  [0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0]
predict:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


ZeroDivisionError: division by zero

In [75]:
import pandas as pd
import pymysql
import numpy as np

def classification_performance_eval(y, y_predict):
    tp, tn, fp, fn = 0,0,0,0
    
    for y, yp in zip(y,y_predict):
        if y == 1 and yp == 1:
            tp += 1
        elif y == 1 and yp == 0:
            fn += 1
        elif y == 0 and yp == 1:
            fp += 1
        else:
            tn += 1
            
    accuracy = (tp+tn)/(tp+tn+fp+fn)
    precision = (tp)/(tp+fp)
    recall = (tp)/(tp+fn)
    f1_score = 2*precision*recall / (precision+recall)
    
    return accuracy, precision, recall, f1_score



conn = pymysql.connect(host='localhost', user='root', password='dkfrpanjdi1~', db='datascience_week6', charset='utf8') 
curs = conn.cursor(pymysql.cursors.DictCursor)
sql = "select * from db_score"
curs.execute(sql)

data  = curs.fetchall()

curs.close()
conn.close()

X = [ (t['homework'], t['discussion'], t['final']) for t in data ]
X = np.array(X)

y = [ 1 if (t['grade'] == 'B') else 0 for t in data]
y = np.array(y)

from sklearn.model_selection import KFold

accuracy = []
precision = []
recall = []
f1_score = []

kf = KFold(n_splits=3, random_state=42, shuffle=True)


from sklearn.linear_model import LogisticRegression



for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    lr = LogisticRegression()
    model = lr.fit(X_train, y_train)
    
    print("test: ", y_test)
    y_predict = model.predict(X_test)
    print("predict: ", y_predict)

    
    acc, prec, rec, f1 = classification_performance_eval(y_test, y_predict)
    accuracy.append(acc)
    precision.append(prec)
    recall.append(rec)
    f1_score.append(f1)

   
import statistics

print("average_accuracy =", statistics.mean(accuracy))
print("average_precision =", statistics.mean(precision))
print("average_recall =", statistics.mean(recall))
print("average_f1_score =", statistics.mean(f1_score))


test:  [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
predict:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


ZeroDivisionError: division by zero